<?php

namespace FriendbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendbookRepository extends EntityRepository
{
}
